### ISSUE TITLE
Development discussion

### ISSUE THREAD

**Issue by Alovchin91** [Alovchin91/opus-winrt#2]
Welcome to the development discussion of **Opus Codec for Windows Runtime** project!
Here we discuss the development process of the project and all related stuff. If you think you could help, feel free to collaborate!

**Comment by Alovchin91** [comment]
**Initial commit** has been done today.
The initial version of _Opus Codec for Windows Runtime_ is now live!

Known issues:
- Strange memory consumption when implementing `MediaStreamSource` for Opus Codec. I'm going to investigate this issue on the first place.
- `TestOpen` methods are not yet implemented.

**Comment by brabebhin** [comment]
I shall test it tomorrow. But where can i find an opus file xD?

**Comment by Alovchin91** [comment]
@mcosmin222 Just use a converter ;) Personally I use Poikosoft EZ CD Audio Converter for many years now.

**Comment by brabebhin** [comment]
Preliminary testing shows that OggOpusFile.Open(IRandomAccessStream) hangs forever, no exception thrown.

**Comment by Alovchin91** [comment]
@mcosmin222 That's strange, it works perfectly for me... I wonder if this is a problem in the official library, it seems opusfile lib is still a work in progress. Could you please give me the file that's causing the problem?

**Comment by brabebhin** [comment]
Sure. How can i do that xD?

**Comment by Alovchin91** [comment]
@mcosmin222 Just upload it to OneDrive, for example, and post here the link :smiley:

**Comment by brabebhin** [comment]
https://onedrive.live.com/redir?resid=8C149B080B3B968F!269367&authkey=!AHOwdXNQAvLGd8M&ithint=folder%2c there we go.

**Comment by Alovchin91** [comment]
@mcosmin222 Hmm... It works with my MediaStreamSource on my Lumia 520 :smiley:
How do you build **opusfile_winrt**? Do you build it in Debug or Release mode?

**Comment by brabebhin** [comment]
debug. why?

**Comment by Alovchin91** [comment]
@mcosmin222 Try building it in Release. For native code this may be pretty important :)

**Comment by Alovchin91** [comment]
@mcosmin222 Hmm, it seems there is really a problem when building in Debug mode. Okay, so for now the workaround is to build the source in Release mode. I will investigate this issue when I have time.
I would also like to ask you for help. It seems you have much more experience in memory profiling, so it would be great if you could investigate the memory issues in the current implementation, please :)

**Comment by brabebhin** [comment]
How can you accuratly calculate the duration of song? This fine format is pretty weird. I can get different durations for same files, depending on the sampling rate used to encoude the file.

**Comment by Alovchin91** [comment]
@mcosmin222 Get the amount of PCM samples using `OggOpusFile.PcmTotal()` and then divide it by sample rate (48000).

**Comment by brabebhin** [comment]
Yeh I figured that just as you posted it xD

I don't have any issues with either memory or play/pause. The issue stays at seeking. I shall see what I be doing wrong. But first I need to fix an ugly dead lock in my app xD. I am, however, testing on a 1GB device. I do not have any 512 with me. I will try it in the emulator later on.

**Comment by brabebhin** [comment]
Ok I fixed seeking xD. Now, onto the 512MB emu

**Comment by brabebhin** [comment]
First pass with debugger attached on 512 MB emulator: no issues

**Comment by brabebhin** [comment]
Second & third pass without debugger on 512 MB emulator: no issues.
I will upload the media stream source to wiki.

**Comment by Alovchin91** [comment]
@mcosmin222 Okay, I've prettified the page a little bit :) Just a tip: you can use ``` sequence to mark the beginning and then the ending of source code section :) You can also start it with, for example, ```cs sequence to mark this code block as C# ("cs"). Example:
```cs
(source code in C#)
```
I escaped the ` character to show this :)

**Comment by Alovchin91** [comment]
@mcosmin222 By memory issue I mean this memory chart behavior:
![Memory chart](https://cloud.githubusercontent.com/assets/8490695/4967930/2dd8fe1e-682a-11e4-80ba-69b78c1a9144.png)
I don't like those peaks, it's not okay.

**Comment by brabebhin** [comment]
Nothing you can do about these. As James said, media stream source was not intended for this. As long as it works fine, there is no problem. The spikes you see are residues from the native decoder methods. You can't match hardware accelerated deciding:)

**Comment by Alovchin91** [comment]
@mcosmin222 I don't see those pikes in other formats (FLAC, Vorbis). Though I suppose the problem is somewhere in Opus libs as they now have 1.1.1-beta version that is "focuses on code optimizations", and moreover, Opusfile lib is pre-release. So maybe the memory consumption problem is somewhere inside those libs, and I'm not going to mess with their internal code :)

**Comment by Alovchin91** [comment]
Alright, so I have fixed stupid errors that were preventing Debug build from working :smiley:

**Comment by Alovchin91** [comment]
@mcosmin222 How do you profile a background task, anyway? :) I can't find any reasonable documentation on this.

**Comment by brabebhin** [comment]
You can't really. I don't think the power tools are too accurate.

I do most memory diagnostics from crash damps and observations and experimentation

**Comment by brabebhin** [comment]
Sooo...what's next xD?

**Comment by Alovchin91** [comment]
@mcosmin222 Your suggestions? :)
Maybe you know the answer to this question: why, while background audio player works perfectly, an attempt to work with IRandomAccessStream from MediaElement in the application fails with System.AccessViolationException? Does this mean that I can't work with file in Music Library from the foreground process? Or am I missing something?

**Comment by brabebhin** [comment]
You mean setting the MediaElement to use a RandomAccessStream as source? If the file is being used by some other process, it will fail, because the media element will lock the file and  prevent other processes from accessing it.

**Comment by brabebhin** [comment]
We could try video codecs. Like MKV

**Comment by Alovchin91** [comment]
@mcosmin222 Alright, forget about AccessViolationException, seems like I found a very nasty bug.
I'm not sure about video, though we could certainly try some codecs. I thought about ALAC and LAME MP3, but first I'd want to make current three codecs shine :) I mean wiki etc.

**Comment by brabebhin** [comment]
Wut bug? mp3 lame should be first. Alac is not really that widely used

**Comment by brabebhin** [comment]
I always wandered what the purpose of the thumbnail property of the media stream source is.

**Comment by Alovchin91** [comment]
@mcosmin222 This was the bug with how the reading operations were made synchronous internally. I use a `DataReader` to read from the `IRandomAccessStream`, and before reading data it requires to `LoadAsync` that data into the reader. I was using this construction to do this:

``` cpp
concurrency::create_task(file_reader->LoadAsync(count)).get();
```

However, when using the MediaStreamSource from MediaElement of foreground app, it sometimes crashed. And while .NET code received System.AccessViolationException, the actual exception was `concurrency::invalid_operation`.
I fixed this in all the three codecs (FLAC, Vorbis, Opus) by introducing a `perform_synchronously` function. I took it from [this](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/4b84a5ec-6b62-4297-9dad-da1c3528e420/wrap-async-operation-in-winrt-component-and-get-exception-in-metro-app?forum=winappswithnativecode) MSDN forums thread.

**Comment by brabebhin** [comment]
Ok. I will update the codes later. I hope microsoft would document these apis better in the future.

**Comment by brabebhin** [comment]
I noticed not a lot of people are using .opus or even know about it...I had quite some weird conversations with some users about this o.O they asked  weather I was part of wierd masonic thing.

**Comment by Alovchin91** [comment]
Hi everyone!
I just made an initial commit of **Universal Windows Platform** version of Opus-WinRT! The code is in **uwp_dev** branch.

**Comment by brabebhin** [comment]
Nice. I will take a look at it once I have installed Windows 10 dev preview on my development machine  :)

**Comment by brabebhin** [comment]
By the way, I need to contact you directly somehow o.O

**Comment by Alovchin91** [comment]
@mcosmin222 It seems BTW that you can use `BackgroundMediaPlayer` in desktop UWP apps, though I didn't check yet.

**Comment by brabebhin** [comment]
mail sent :package:
