### ISSUE TITLE
Include to existing UWP project

### ISSUE THREAD

**Issue by Vanhara** [Alovchin91/opus-winrt#3]
Hello,

I am trying to include this project into existing UWP project e.g. UWP VOIP sample, but im still getting plenty of errors.

I tried to include builds (.lib) to project, reference projects itself, use just the files in project, but everything went wrong. Would you be so kind to give me at least some help notes on this. I think this would be very helpfull also to other people developing for UWP.

Thank you.

**Comment by Alovchin91** [comment]
Hi @Vanhara,
You need to reference .winmd file in your project, and the implementation .dll must be in the same directory. I'll do my best to release a NuGet package till the end of this week.

**Comment by Vanhara** [comment]
Thx Alovchin. The thing is if i set in properties to create .winmd file, it is still no created (i cant find it anywhere in build folders). But i managed to link .lib to linker and it finally worked (lib in solution folder and path to headers in file using the lib) - so no problem there. Now I am facing another issue - since UWP is for 3 architectures (x86, x64 and ARM)  - some c files throws #errors that only x86 and x64 builds are supported, e.g. "xmmintrin.h" Do you think if there is any way to build this libs for ARM?

**Comment by Makzz90** [comment]
Александр, у нас проблемка с компиляцией под ЮВП. Напиши пожалуйста мне в вк /makzz.
