### ISSUE TITLE
Trouble opening in VS2015 update 3

### ISSUE THREAD

**Issue by clinton05** [Alovchin91/opus-winrt#4]
Hi I'm having trouble opening this in vs 2015, update 3. 
_"vcxproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=659044&projecttype=8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942"_

Any work around?

**Comment by Alovchin91** [comment]
@clinton05 Hi! I'll look into it.

**Comment by clinton05** [comment]
Thanks !
